#Para el AWS
#server.port=5000
#spring.datasource.url=jdbc:postgresql://db-prevdengue.cfo6cccou8lb.us-east-2.rds.amazonaws.com/PrevDengueDB
#spring.datasource.username=postgres
#spring.datasource.password=prevdengue2026
#spring.jpa.hibernate.ddl-auto=update
jwt.secret=unaClaveSecretaSegura123RAKDJLKASJDLKASJDLAKJDAKLJGKLANDJQKN

#Para el Local
spring.application.name=PrevDengue
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/dbprevdengue
spring.datasource.username=postgres
spring.datasource.password=1234
server.port=8080