server.port=5000
spring.datasource.url=jdbc:postgresql://prevdengue.cfo6cccou8lb.us-east-2.rds.amazonaws.com/PrevDengueDB
spring.datasource.username=postgres
spring.datasource.password=prevdengue2026
spring.jpa.hibernate.ddl-auto=update
jwt.secret=unaClaveSecretaSegura123RECTMREHIJODEPUTA