# ==========================================
# CONFIGURACIÓN GENERAL DEL PROYECTO
# ==========================================
spring.application.name=PrevDengue
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# ☁️ CONFIGURACIÓN NUBE (RENDER - PRODUCCIÓN)
# ==========================================
spring.datasource.url=jdbc:postgresql://dpg-d95et7jtqb8s73eoqagg-a.oregon-postgres.render.com/prevdengue_db
#postgresql://prevdengue_db_user:16dM1HqBpQrFDngaWz9mO3sDh84LHtHD@dpg-d95et7jtqb8s73eoqagg-a.oregon-postgres.render.com/prevdengue_db#
spring.datasource.username=prevdengue_db_user
spring.datasource.password=16dM1HqBpQrFDngaWz9mO3sDh84LHtHD

# ==========================================
# 💻 CONFIGURACIÓN LOCAL (DESARROLLO)
# (Para probar en tu PC, comenta las 3 líneas de arriba y descomenta las 3 de abajo)
# ==========================================
#spring.datasource.url=jdbc:postgresql://localhost/baseejemplo
#spring.datasource.username=postgres
#spring.datasource.password=1234

# ==========================================
# 🔐 SEGURIDAD JWT
# ==========================================
jwt.secret=unaClaveSecretaSegura123RAKDJLKASJDLKASJDLAKJDAKLJGKLANDJQKN

# ==========================================
# 🌐 PUERTO DEL SERVIDOR
# ==========================================
server.port=8080